#!/bin/zsh

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# sudo not required for some system commands
for command in mount umount sv apt updatedb su shutdown poweroff reboot lsof update-alternatives ; do
	alias $command="sudo $command"
done; unset command

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Get week number
alias week='date +%V'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv"

# Youtube-dl shortcuts
alias \
	yt="youtube-dl --embed-metadata -i" \
	yta="yt -x -f bestaudio/best"

# Other
alias \
	ffmpeg="ffmpeg -hide_banner" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	javahome="dirname $(dirname $(readlink -f $(which javac)))"

# List only directories
# shellcheck disable=SC2139
alias \
	lsd="ls -lhF ${colorflag} | grep --color=never '^d'"

# These common commands are just too long! Abbreviate them.
alias \
	c="echo something special!" \
	g="git" \
	trem="transmission-remote" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	a="apt" \
	asearch="apt search" \
	ainstall="apt install" \
	aupdate="apt update" \
	aupgrade="apt upgrade" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	open="xdg-open" \
	run="gtk-launch" \
	activeports="lsof -i -P -n | grep LISTEN" \
	untar="tar -xvf" \
	ualt="update-alternatives" \
	switchjava="ualt --config java" \
	z="zathura"

# Go to
alias \
	aptpacks="cd /etc/apt/" \
	projects="cd ~/Projects" \
	dwln="cd ~/Downloads" \
	docs="cd ~/Documents" \
	tuts="cd ~/Tutorials" \
	music="cd ~/Music"

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# IP addresses
alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="sudo ifconfig | grep -Eo 'inet (addr:)?([0-9]*\\.){3}[0-9]*' | grep -Eo '([0-9]*\\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ips="sudo ifconfig -a | grep -o 'inet6\\? \\(addr:\\)\\?\\s\\?\\(\\(\\([0-9]\\+\\.\\)\\{3\\}[0-9]\\+\\)\\|[a-fA-F0-9:]\\+\\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\\: .*|GET \\/.*\""

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"

# Trim new lines and copy to clipboard
alias c="tr -d '\\n' | xclip -selection primary"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	# shellcheck disable=SC2139,SC2140
	alias "$method"="lwp-request -m \"$method\""
done

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# vhosts
alias hosts='sudo vim /etc/hosts'

#
# NOTE: clipboard doesn't seem to work in Debian env.
#

# copy working directory
alias cwd='pwd | tr -d "\r\n" | xclip -selection primary'

# Pipe my public key to my clipboard.
alias pubkey="more ~/.ssh/id_ed25519.pub | xclip -selection primary | echo '=> Public key copied to pasteboard.'"

# Pipe my private key to my clipboard.
alias prikey="more ~/.ssh/id_ed25519 | xclip -selection primary | echo '=> Private key copied to pasteboard.'"

# Screenshot
# Source: https://wiki.debian.org/ScreenShots
alias capture="xwd -root | xwdtopnm | pnmtopng > capture.png"

alias \
	wifipass="sudo vim /etc/NetworkManager/system-connections/" \
	lswifi="nmcli device wifi list" \
	whichwifi="iwgetid -r"
